### ISSUE TITLE
there is something wrong ,but i do not confirm it`s work fine ?

### ISSUE THREAD

**Issue by taylorwin** [ajinabraham/Mobile-Security-Framework-MobSF#115]
dex2jar C:\MobSF\uploads/fbf70dd97d0440dbbcd6e7ddb54a499e/classes.dex -> C:\MobSF\uploads\fbf70dd97d0440dbbcd6e7ddb54a499e\classes.jar
java.lang.IndexOutOfBoundsException: Index: 24, Size: 24
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at jd.fI.a(Unknown Source)
	at jd.fI.a(Unknown Source)
	at jd.af.b(Unknown Source)
	at jd.af.a(Unknown Source)
	at jd.af.a(Unknown Source)
	at jd.i.a(Unknown Source)
	at jd.ide.intellij.JavaDecompiler.decompile(Native Method)
	at jd.core.Decompiler.decompile(Decompiler.java:47)
	at jd.core.Decompiler.decompileToDir(Decompiler.java:56)
	at jd.core.Main.main(Main.java:16)
java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at jd.fI.a(Unknown Source)
	at jd.fI.a(Unknown Source)
	at jd.af.b(Unknown Source)
	at jd.af.a(Unknown Source)
	at jd.af.a(Unknown Source)
	at jd.i.a(Unknown Source)
	at jd.ide.intellij.JavaDecompiler.decompile(Native Method)
	at jd.core.Decompiler.decompile(Decompiler.java:47)
	at jd.core.Decompiler.decompileToDir(Decompiler.java:56)
	at jd.core.Main.main(Main.java:16)

.........................................

Decompiled 1496 classes
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - C:\MobSF\uploads/39f851275229de2e08041df1c5856
d35/java_source/
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
        at strings.StringsXML.run(StringsXML.java:84)
        at strings.StringsXML.main(StringsXML.java:151)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
        at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
        ... 5 more

[INFO] Connecting to Database

**Comment by ajinabraham** [comment]
This is fine these are some exceptions caused on dex2jar and string extraction utlity

**Comment by taylorwin** [comment]
thanks~~
