### ISSUE TITLE
Show screen feature not working

### ISSUE THREAD

**Issue by tusnindas** [ajinabraham/Mobile-Security-Framework-MobSF#122]
[29/Mar/2016 11:11:51]"GET /static/screen/screen.png?1459230111323 HTTP/1.1" 404
 1678
[29/Mar/2016 11:11:51]"GET /static/screen/screen.png?1459230111413 HTTP/1.1" 404
 1678
[29/Mar/2016 11:11:51]"GET /static/screen/screen.png?1459230111622 HTTP/1.1" 404
 1678

[INFO] Invoking ScreenCast Service in VM/Device

[INFO] Getting ADB Location
[29/Mar/2016 11:11:51]"GET /static/screen/screen.png?1459230111714 HTTP/1.1" 404
 1678
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a
 security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is
 a security risk. Please fix.
[29/Mar/2016 11:11:51]"GET /static/screen/screen.png?1459230111922 HTTP/1.1" 404
 1678

[INFO] ScreenCast Service Status: off
[29/Mar/2016 11:11:52]"POST /ScreenCast/ HTTP/1.1" 200 17
[29/Mar/2016 11:11:52]"GET /static/screen/screen.png?1459230112014 HTTP/1.1" 404
 1678
Traceback (most recent call last):
  File "C:\Python27\lib\wsgiref\handlers.py", line 86, in run
    self.finish_response()
  File "C:\Python27\lib\wsgiref\handlers.py", line 128, in finish_response
    self.write(data)
  File "C:\Python27\lib\wsgiref\handlers.py", line 212, in write
    self.send_headers()
  File "C:\Python27\lib\wsgiref\handlers.py", line 270, in send_headers
    self.send_preamble()
  File "C:\Python27\lib\wsgiref\handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "C:\Python27\lib\socket.py", line 328, in write
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in yo
ur host machine
[29/Mar/2016 11:11:52]"GET /static/screen/screen.png?1459230112014 HTTP/1.1" 500
 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51079)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\site-packages\django\core\servers\basehttp.py", line 102
, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 283, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in yo
ur host machine
----------------------------------------

**Comment by ajinabraham** [comment]
The error says 
"An established connection was aborted by the software in yo
ur host machine"

Do you have an Firewall or AV preventing this. This is not a MobSF issue.
