### ISSUE TITLE
Don't Play Around. An Error just popped in! I/O operation failed.

### ISSUE THREAD

**Issue by voriya74** [ajinabraham/Mobile-Security-Framework-MobSF#164]
Console logs:

C:\Python27>python.exe C:\Mobile-Security-Framework-MobSF-0.8.8\Mobile-Security-
Framework-MobSF-0.8.8\manage.py runserver

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!
Performing system checks...

System check identified no issues (0 silenced).
May 25, 2016 - 15:30:08
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[INFO] Mobile Security Framework v0.8.8beta
[25/May/2016 15:30:19]"GET / HTTP/1.1" 200 7201
[INFO] MIME Type: application/octet-stream FILE: fennec-44.0b8.en-US.android-arm
.apk
[25/May/2016 15:30:30]"POST /Upload/ HTTP/1.1" 200 158
[INFO] Starting Analysis on : fennec-44.0b8.en-US.android-arm.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Signer Certificate
[INFO] DEX -> JAR
[INFO] Running JAVA Path fix in Windows
Error: Could not find or load main class com.googlecode.dex2jar.tools.Dex2jarCmd

[INFO] DEX -> SMALI
[INFO] JAR -> JAVA
java.io.FileNotFoundException: C:\Mobile-Security-Framework-MobSF-0.8.8\Mobile-S
ecurity-Framework-MobSF-0.8.8\uploads\22da35637f936c33368f77ee77efd842\classes.j
ar (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at jd.core.Decompiler.decompile(Decompiler.java:28)
        at jd.core.Decompiler.decompileToDir(Decompiler.java:56)
        at jd.core.Main.main(Main.java:16)
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - C:\Mobile-Security-Framework-MobSF-0.8.8\Mobil
e-Security-Framework-MobSF-0.8.8\uploads/22da35637f936c33368f77ee77efd842/java_s
ource/
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[25/May/2016 15:31:28]"GET /StaticAnalyzer/?name=fennec-44.0b8.en-US.android-arm
.apk&type=apk&checksum=22da35637f936c33368f77ee77efd842 HTTP/1.1" 200 2948

**Comment by voriya74** [comment]
The actual error here was : Error: Could not find or load main class com.googlecode.dex2jar.tools.Dex2jarCmd
If u get same error download MobSF version 0.8.8.1
It will work
