### ISSUE TITLE
UnicodeDecodeError happens while open localhost: 127.0.0.1:8000

### ISSUE THREAD

**Issue by bookjoy** [ajinabraham/Mobile-Security-Framework-MobSF#242]
Version: v0.9.1 beta
OS:  windows 7
Python Version: 2.7.6

My log files:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
    ctype = ctype.encode(default_encoding) # omit in 3.x!
[12/Oct/2016 17:03:11] "GET /static/css/dropzone.css HTTP/1.1" 500 59
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
[12/Oct/2016 17:03:11] "GET /static/js/dropzone.js HTTP/1.1" 500 59
[12/Oct/2016 17:03:11] "GET /static/js/jquery.min.js HTTP/1.1" 500 59
[12/Oct/2016 17:03:11] "GET /static/css/bootstrap.min.css HTTP/1.1" 500 59
Traceback (most recent call last):
  File "D:\Python276\lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "D:\Python276\lib\site-packages\django\core\handlers\wsgi.py", line 170,
in __call__
Traceback (most recent call last):
    response = self.get_response(request)
  File "D:\Python276\lib\wsgiref\handlers.py", line 85, in run
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 54, in get_response
    self.result = application(self.environ, self.start_response)
    return self.serve(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 64, in __call__
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 47, in serve
    return super(StaticFilesHandler, self).__call__(environ, start_response)
    return serve(request, self.file_path(request.path), insecure=True)
  File "D:\Python276\lib\site-packages\django\core\handlers\wsgi.py", line 170,
in __call__
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\views.py", lin
e 40, in serve
    response = self.get_response(request)
    return static.serve(request, path, document_root=document_root, **kwargs)
  File "D:\Python276\lib\site-packages\django\views\static.py", line 66, in serv
e
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 54, in get_response
    content_type, encoding = mimetypes.guess_type(fullpath)
    return self.serve(request)
  File "D:\Python276\lib\mimetypes.py", line 297, in guess_type
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 47, in serve
    init()
    return serve(request, self.file_path(request.path), insecure=True)
  File "D:\Python276\lib\mimetypes.py", line 358, in init
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\views.py", lin
e 40, in serve
    db.read_windows_registry()
    return static.serve(request, path, document_root=document_root, **kwargs)
  File "D:\Python276\lib\mimetypes.py", line 258, in read_windows_registry
  File "D:\Python276\lib\site-packages\django\views\static.py", line 66, in serv
e
    for subkeyname in enum_types(hkcr):
  File "D:\Python276\lib\mimetypes.py", line 249, in enum_types
    ctype = ctype.encode(default_encoding) # omit in 3.x!
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
    content_type, encoding = mimetypes.guess_type(fullpath)
  File "D:\Python276\lib\mimetypes.py", line 297, in guess_type
    init()
  File "D:\Python276\lib\mimetypes.py", line 358, in init
    db.read_windows_registry()
  File "D:\Python276\lib\mimetypes.py", line 258, in read_windows_registry
    for subkeyname in enum_types(hkcr):
[12/Oct/2016 17:03:11] "GET /static/js/bootstrap.min.js HTTP/1.1" 500 59
  File "D:\Python276\lib\mimetypes.py", line 249, in enum_types
    ctype = ctype.encode(default_encoding) # omit in 3.x!
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
[12/Oct/2016 17:03:11] "GET /static/js/jquery.min.js HTTP/1.1" 500 59
Traceback (most recent call last):
  File "D:\Python276\lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "D:\Python276\lib\site-packages\django\core\handlers\wsgi.py", line 170,
in __call__
    response = self.get_response(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 54, in get_response
    return self.serve(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\views.py", lin
e 40, in serve
    return static.serve(request, path, document_root=document_root, **kwargs)
  File "D:\Python276\lib\site-packages\django\views\static.py", line 66, in serv
e
    content_type, encoding = mimetypes.guess_type(fullpath)
Traceback (most recent call last):
  File "D:\Python276\lib\mimetypes.py", line 297, in guess_type
  File "D:\Python276\lib\wsgiref\handlers.py", line 85, in run
    init()
    self.result = application(self.environ, self.start_response)
  File "D:\Python276\lib\mimetypes.py", line 358, in init
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 64, in __call__
    db.read_windows_registry()
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "D:\Python276\lib\mimetypes.py", line 258, in read_windows_registry
  File "D:\Python276\lib\site-packages\django\core\handlers\wsgi.py", line 170,
in __call__
    for subkeyname in enum_types(hkcr):
    response = self.get_response(request)
  File "D:\Python276\lib\mimetypes.py", line 249, in enum_types
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 54, in get_response
    ctype = ctype.encode(default_encoding) # omit in 3.x!
    return self.serve(request)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\views.py", lin
e 40, in serve
    return static.serve(request, path, document_root=document_root, **kwargs)
  File "D:\Python276\lib\site-packages\django\views\static.py", line 66, in serv
e
    content_type, encoding = mimetypes.guess_type(fullpath)
  File "D:\Python276\lib\mimetypes.py", line 297, in guess_type
    init()
  File "D:\Python276\lib\mimetypes.py", line 358, in init
[12/Oct/2016 17:03:11] "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1"
 500 59
    db.read_windows_registry()
  File "D:\Python276\lib\mimetypes.py", line 258, in read_windows_registry
    for subkeyname in enum_types(hkcr):
  File "D:\Python276\lib\mimetypes.py", line 249, in enum_types
    ctype = ctype.encode(default_encoding) # omit in 3.x!
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
[12/Oct/2016 17:03:11] "GET /static/js/dropzone.js HTTP/1.1" 500 59
Traceback (most recent call last):
  File "D:\Python276\lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "D:\Python276\lib\site-packages\django\core\handlers\wsgi.py", line 170,
in __call__
    response = self.get_response(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 54, in get_response
    return self.serve(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\views.py", lin
e 40, in serve
    return static.serve(request, path, document_root=document_root, **kwargs)
  File "D:\Python276\lib\site-packages\django\views\static.py", line 66, in serv
e
    content_type, encoding = mimetypes.guess_type(fullpath)
  File "D:\Python276\lib\mimetypes.py", line 297, in guess_type
    init()
  File "D:\Python276\lib\mimetypes.py", line 358, in init
Traceback (most recent call last):
  File "D:\Python276\lib\wsgiref\handlers.py", line 85, in run
    db.read_windows_registry()
    self.result = application(self.environ, self.start_response)
  File "D:\Python276\lib\mimetypes.py", line 258, in read_windows_registry
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 64, in __call__
    for subkeyname in enum_types(hkcr):
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "D:\Python276\lib\mimetypes.py", line 249, in enum_types
  File "D:\Python276\lib\site-packages\django\core\handlers\wsgi.py", line 170,
in __call__
    ctype = ctype.encode(default_encoding) # omit in 3.x!
    response = self.get_response(request)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 54, in get_response
    return self.serve(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\views.py", lin
e 40, in serve
    return static.serve(request, path, document_root=document_root, **kwargs)
  File "D:\Python276\lib\site-packages\django\views\static.py", line 66, in serv
e
[12/Oct/2016 17:03:11] "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 500 59
    content_type, encoding = mimetypes.guess_type(fullpath)
  File "D:\Python276\lib\mimetypes.py", line 297, in guess_type
    init()
  File "D:\Python276\lib\mimetypes.py", line 358, in init
    db.read_windows_registry()
  File "D:\Python276\lib\mimetypes.py", line 258, in read_windows_registry
    for subkeyname in enum_types(hkcr):
  File "D:\Python276\lib\mimetypes.py", line 249, in enum_types
    ctype = ctype.encode(default_encoding) # omit in 3.x!
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
[12/Oct/2016 17:03:11] "GET /static/css/dropzone.css HTTP/1.1" 500 59
Traceback (most recent call last):
  File "D:\Python276\lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "D:\Python276\lib\site-packages\django\core\handlers\wsgi.py", line 170,
in __call__
    response = self.get_response(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 54, in get_response
    return self.serve(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\views.py", lin
e 40, in serve
    return static.serve(request, path, document_root=document_root, **kwargs)
  File "D:\Python276\lib\site-packages\django\views\static.py", line 66, in serv
e
    content_type, encoding = mimetypes.guess_type(fullpath)
  File "D:\Python276\lib\mimetypes.py", line 297, in guess_type
    init()
  File "D:\Python276\lib\mimetypes.py", line 358, in init
    db.read_windows_registry()
  File "D:\Python276\lib\mimetypes.py", line 258, in read_windows_registry
    for subkeyname in enum_types(hkcr):
  File "D:\Python276\lib\mimetypes.py", line 249, in enum_types
    ctype = ctype.encode(default_encoding) # omit in 3.x!
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
[12/Oct/2016 17:03:11] "GET /static/js/bootstrap.min.js HTTP/1.1" 500 59
Traceback (most recent call last):
  File "D:\Python276\lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "D:\Python276\lib\site-packages\django\core\handlers\wsgi.py", line 170,
in __call__
    response = self.get_response(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 54, in get_response
    return self.serve(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\views.py", lin
e 40, in serve
    return static.serve(request, path, document_root=document_root, **kwargs)
  File "D:\Python276\lib\site-packages\django\views\static.py", line 66, in serv
e
    content_type, encoding = mimetypes.guess_type(fullpath)
  File "D:\Python276\lib\mimetypes.py", line 297, in guess_type
    init()
  File "D:\Python276\lib\mimetypes.py", line 358, in init
    db.read_windows_registry()
  File "D:\Python276\lib\mimetypes.py", line 258, in read_windows_registry
    for subkeyname in enum_types(hkcr):
  File "D:\Python276\lib\mimetypes.py", line 249, in enum_types
    ctype = ctype.encode(default_encoding) # omit in 3.x!
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
[12/Oct/2016 17:03:11] "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1"
 500 59
Traceback (most recent call last):
  File "D:\Python276\lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "D:\Python276\lib\site-packages\django\core\handlers\wsgi.py", line 170,
in __call__
    response = self.get_response(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 54, in get_response
    return self.serve(request)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\handlers.py",
line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "D:\Python276\lib\site-packages\django\contrib\staticfiles\views.py", lin
e 40, in serve
    return static.serve(request, path, document_root=document_root, **kwargs)
  File "D:\Python276\lib\site-packages\django\views\static.py", line 66, in serv
e
    content_type, encoding = mimetypes.guess_type(fullpath)
  File "D:\Python276\lib\mimetypes.py", line 297, in guess_type
    init()
  File "D:\Python276\lib\mimetypes.py", line 358, in init
    db.read_windows_registry()
  File "D:\Python276\lib\mimetypes.py", line 258, in read_windows_registry
    for subkeyname in enum_types(hkcr):
  File "D:\Python276\lib\mimetypes.py", line 249, in enum_types
    ctype = ctype.encode(default_encoding) # omit in 3.x!
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal
not in range(128)
[12/Oct/2016 17:03:11] "GET /static/favicon.ico HTTP/1.1" 500 59

**Comment by TiberiumPY** [comment]
Can you try latest Python? There's already 2.7.12

**Comment by bookjoy** [comment]
It works on my installation of Python2.7.12.  Thx a lot.

**Comment by ajinabraham** [comment]
Tracking Separately.

**Comment by ajinabraham** [comment]
Hoping that this is Unicode Issues with Python 2.7.6
