### ISSUE TITLE
Unicode Bugs to Fix 

### ISSUE THREAD

**Issue by ajinabraham** [ajinabraham/Mobile-Security-Framework-MobSF#246]
- [x] #236
- [x] #243 
- [x] #222
- [x] #205
- [x] #196

**Comment by ajinabraham** [comment]
Fixed all unicode bugs

**Comment by pablovidelayanez** [comment]
@ajinabraham are u sure this it's fixed ? 
i have the last commit and this error show me.

[ERROR] Unzipping Error (E:\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\shared_func.py, LINE 91 "with io.open(outfile, mode='wb') as f:"): [Errno 22] Invalid argument: u'E:\\Mobile-Security-Framework-MobSF\\uploads/b1a7c5c8b075526500aa3367dc6fc929/\x0c\u2028\x0c.xml'



[2017-01-16 11:41:39]
[ERROR] Pasrsing AndroidManifest.xml (E:\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\manifest_analysis.py, LINE 27 "manifest = minidom.parseString(dat)"): not well-formed (invalid token): line 5, column 1
[WARNING] Using Fake XML to continue the Analysis
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Reading Code Signing Certificate
[INFO] DEX -> JAR
[INFO] Using JAR converter - dex2jar
[INFO] Running JAVA path fix in Windows
dex2jar E:\Mobile-Security-Framework-MobSF\uploads/b1a7c5c8b075526500aa3367dc6fc929/classes.dex -> E:\Mobile-Security-Framework-MobSF\uploads\b1a7c5c8b075526500aa3367dc6fc929\classes.jar
java.nio.file.NoSuchFileException: E:\Mobile-Security-Framework-MobSF\uploads\b1a7c5c8b075526500aa3367dc6fc929\classes.dex
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at com.googlecode.d2j.reader.zip.ZipUtil.readDex(ZipUtil.java:57)
        at com.googlecode.d2j.reader.zip.ZipUtil.readDex(ZipUtil.java:53)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
[INFO] DEX -> SMALI
Can't find the file E:\Mobile-Security-Framework-MobSF\uploads/b1a7c5c8b075526500aa3367dc6fc929/classes.dex
[INFO] JAR -> JAVA
Processing E:\Mobile-Security-Framework-MobSF\uploads/b1a7c5c8b075526500aa3367dc6fc929/classes.jar (use silent to silence)
Exception analysing jar org.benf.cfr.reader.util.ConfusedCFRException: No such jar file E:\Mobile-Security-Framework-MobSF\uploads/b1a7c5c8b075526500aa3367dc6fc929/classes.jar
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - E:\Mobile-Security-Framework-MobSF\uploads/b1a7c5c8b075526500aa3367dc6fc929/java_source/
[INFO] Performing Malware Check on extracted Domains
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:165)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:133)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:108)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
        at strings.StringsXML.run(StringsXML.java:84)
        at strings.StringsXML.main(StringsXML.java:151)

[INFO] Connecting to Database

[INFO] Saving to Database

[2017-01-16 11:41:50]
[ERROR] Saving to DB (E:\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\db_interaction.py, LINE 236 "static_db.save()"): table StaticAnalyzer_staticanalyzerandroid has no column named BROWSABLE

**Comment by ajinabraham** [comment]
You need to share the APK that caused this issue.

Also to fix the last error 
```
[2017-01-16 11:41:50]
[ERROR] Saving to DB (E:\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\db_interaction.py, LINE 236 "static_db.save()"): table StaticAnalyzer_staticanalyzerandroid has no column named BROWSABLE
```
Read: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf
