### ISSUE TITLE
Can't get proxy to work

### ISSUE THREAD

**Issue by rip32700** [ajinabraham/Mobile-Security-Framework-MobSF#277]
Hi,

I am trying to get the proxy working without any success. I followed all the steps in the documentation, the interfaces and IP addresses are setup correctly. When I try to access the Internet while the proxy is running, I get a net::ERR_TIMED_OUT. 

When I connect to the proxy from another VM, I get through and the browser loads the requested site. Looking into the generated WebTraffic.txt logs, the response is "RESPONSE: 599 Unknown" for every request. When I set the proxy settings to None within the VM, it works normally.

Thanks in advance!

**Comment by ajinabraham** [comment]
This is strange. Can you share the proxy logs. Get the logs from logs/webproxy.log

**Comment by rip32700** [comment]
The proxy logs reveal hundreds of the same error:

`[E 161129 01:04:46 iostream:546] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 507, in _handle_events
        self._handle_connect()
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 1376, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 522, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
        _context=self)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 572, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname
[E 161129 01:04:46 iostream:546] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 507, in _handle_events
        self._handle_connect()
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 1376, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 522, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
        _context=self)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 572, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname
[E 161129 01:04:46 ioloop:633] Exception in callback None
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
        handler_func(fd_obj, events)
      File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 507, in _handle_events
        self._handle_connect()
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 1376, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 522, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
        _context=self)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 572, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname
[E 161129 01:04:46 ioloop:633] Exception in callback None
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
        handler_func(fd_obj, events)
      File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 507, in _handle_events
        self._handle_connect()
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 1376, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 522, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
        _context=self)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 572, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname
[E 161129 01:04:49 iostream:546] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 507, in _handle_events
        self._handle_connect()
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 1376, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 522, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
        _context=self)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 572, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname
[E 161129 01:04:49 iostream:546] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 507, in _handle_events
        self._handle_connect()
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 1376, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 522, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
        _context=self)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 572, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname
[E 161129 01:04:49 ioloop:633] Exception in callback None
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
        handler_func(fd_obj, events)
      File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 507, in _handle_events
        self._handle_connect()
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 1376, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 522, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
        _context=self)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 572, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname
[E 161129 01:04:49 ioloop:633] Exception in callback None
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
        handler_func(fd_obj, events)
      File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 507, in _handle_events
        self._handle_connect()
      File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 1376, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 522, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
        _context=self)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 572, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname`

**Comment by ajinabraham** [comment]
This is fine. I just tested the proxy in my environment and everything works fine. Make sure that there is no port conflicts and proxy is able to run.

**Comment by NeuroWinter** [comment]
I am getting the same issue...

**Comment by KotamRamana** [comment]
I am getting same issue on .0.9.5.2Beta
 Error log:
[E 170510 12:18:18 ioloop:638] Exception in callback None
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\tornado\ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "C:\Python27\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "C:\Python27\lib\site-packages\tornado\iostream.py", line 515, in _handle_events
        self._handle_connect()
      File "C:\Python27\lib\site-packages\tornado\iostream.py", line 1427, in _handle_connect
        do_handshake_on_connect=False)
      File "C:\Python27\lib\site-packages\tornado\netutil.py", line 526, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "C:\Python27\lib\ssl.py", line 352, in wrap_socket
        _context=self)
      File "C:\Python27\lib\ssl.py", line 550, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname

**Comment by ajinabraham** [comment]
These errors from logs are normal. Windows is known to have port blocking issues. Try disabling your firewall and try again

**Comment by KotamRamana** [comment]
Hi Ajin,
I have tried using airtel dongle also without proxy. I had no luck. Regards and Thanks, 
K.V.Ramanamurthy, 
B210,Pariwar Pendant Apartment, 1st A Cross, 3 main road,Doctors Layout, Kodichikkanahalli,Bengaluru - 560076, +91-7028082804(Mobile) 

    On Thursday, May 11, 2017 1:43 PM, Ajin Abraham <notifications@github.com> wrote:
 

 These errors from logs are normal. Windows is known to have port blocking issues. Try disabling your firewall and try again—
