### ISSUE TITLE
AttributeError: ConfigParser instance has no attribute '__getitem__'

### ISSUE THREAD

**Issue by KevinKien** [ajinabraham/Mobile-Security-Framework-MobSF#278]
I run MobSF on windows 10. When run command "python manage.py runserver", I receive a error

> C:\MobSF>python manage.py runserver
[INFO] Running first time setup for windows.
[*] Reading config file..
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
367, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
316, in execute
    settings.INSTALLED_APPS
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 53, in __ge
tattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _set
up
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 97, in __in
it__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\MobSF\MobSF\settings.py", line 367, in <module>
    windows_setup.install_locally(MobSF_HOME)
  File "C:\MobSF\install\windows\setup.py", line 366, in install_locally
    rewrite_local_config(mobsf_home)
  File "C:\MobSF\install\windows\setup.py", line 349, in rewrite_local_config
    CONFIG['MobSF']['subdir_tools'] = mobsf_home + "\\StaticAnalyzer\\tools\\win
dows\\"
AttributeError: ConfigParser instance has no attribute '__getitem__'

**Comment by DominikSchlecht** [comment]
Please have a look at #273, most probably this is due to insufficient read/write-privs to the config directory.
