### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by viris** [ajinabraham/Mobile-Security-Framework-MobSF#293]
I am getting this on latest Kali version, fully patched.
It looks like there are some problems with OpenSSL and python:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843614

WARNING] Could not find VirtualBox path.
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f9c48b382a8>
Traceback (most recent call last):
  File "/root/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/root/.local/lib/python2.7/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/root/.local/lib/python2.7/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/root/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/root/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/root/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/root/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 305, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 298, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/MobSF/MobSF/urls.py", line 4, in <module>
    import DynamicAnalyzer.views.android
  File "/root/MobSF/DynamicAnalyzer/views/android.py", line 9, in <module>
    from DynamicAnalyzer.pyWebProxy.pywebproxy import *
  File "/root/MobSF/DynamicAnalyzer/pyWebProxy/pywebproxy.py", line 51, in <module>
    from DynamicAnalyzer.pyWebProxy.socket_wrapper import wrap_socket
  File "/root/MobSF/DynamicAnalyzer/pyWebProxy/socket_wrapper.py", line 35, in <module>
    from gen_cert import gen_signed_cert
  File "/root/MobSF/DynamicAnalyzer/pyWebProxy/gen_cert.py", line 32, in <module>
    from OpenSSL import crypto
  File "/root/.local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by ajinabraham** [comment]
Could you please install pyOpenSSL 16.2.0 and see if this is fixed?

**Comment by viris** [comment]
changed to pyOpenSSL==16.2.0 in requirements.txt file and now looks ok :)
Thanks!

**Comment by ajinabraham** [comment]
Fixed this in the master as well

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!
