### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by rajeshmajumdar** [ajinabraham/Mobile-Security-Framework-MobSF#301]
After getting a warning VirtualBox Path not found, it shows me this error. Should I install VirtualBox, to simply run manage.py runserver

**Comment by rajeshmajumdar** [comment]
Now after I installed VirtualBox, I am getting the same RuntimeError, but this it isn't showing the warning about virtualbox path not found but showing unhandled exception
Unhandled exception in thread started by <function wrapper at 0x0000000003C35CF8>
Traceback (most recent call last):
  File "C:\Users\xxxxxxxxxx\AppData\Roaming\Python\Python27\site-packages\django\utils\autoreload.py", line 226, in wrapper

**Comment by ajinabraham** [comment]
Share the complete logs.

**Comment by meloyi** [comment]
I have the same problem with rajeshmajumdar. 
This is my log:
`
F:\Mobile-Security-Framework-MobSF-master>python manage.py runserver

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!
Unhandled exception in thread started by <function wrapper at 0x02DE9AF0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27\lib\site-packages\django\contrib\auth\models.py", line 300, in <module>
    class AbstractUser(AbstractBaseUser, PermissionsMixin):
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 274, in __new__
    new_class.add_to_class(field.name, new_field)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Python27\lib\site-packages\django\db\models\fields\__init__.py", line 694, in contribute_to_class
    cls._meta.add_field(self)
  File "C:\Python27\lib\site-packages\django\db\models\options.py", line 277, in add_field
    self.local_fields.insert(bisect(self.local_fields, field), field)
  File "C:\Python27\lib\functools.py", line 56, in <lambda>
    '__lt__': [('__gt__', lambda self, other: other < self),
  File "C:\Python27\lib\functools.py", line 56, in <lambda>
    '__lt__': [('__gt__', lambda self, other: other < self),
  File "C:\Python27\lib\functools.py", line 56, in <lambda>
    '__lt__': [('__gt__', lambda self, other: other < self),
  File "C:\Python27\lib\functools.py", line 56, in <lambda>
    '__lt__': [('__gt__', lambda self, other: other < self),
		...(all the repeated log)
  File "C:\Python27\lib\functools.py", line 56, in <lambda>
    '__lt__': [('__gt__', lambda self, other: other < self),
  File "C:\Python27\lib\functools.py", line 56, in <lambda>
    '__lt__': [('__gt__', lambda self, other: other < self),
RuntimeError: maximum recursion depth exceeded in cmp
`
I run MobSF in Win8.1. Is the above log what you want? @ajinabraham

**Comment by ajinabraham** [comment]
Have a look into http://stackoverflow.com/questions/16259729/django-python-manage-py-runserver-gives-runtimeerror-maximum-recursion-depth-e
Not a MobSF issue. hence closing this
