### ISSUE TITLE
Error during static code analysis

### ISSUE THREAD

**Issue by Emi1305** [ajinabraham/Mobile-Security-Framework-MobSF#308]
When I try to statically analyze an APK file I get an error right after the `Extracting Strings from APK` step.

The stacktrace is the following:

```
[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
	at strings.StringsXML.run(StringsXML.java:84)
	at strings.StringsXML.main(StringsXML.java:151)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 5 more

[INFO] Connecting to Database

[INFO] Saving to Database

[2017-01-03 21:03:14]
[ERROR] Saving to DB (/opt/MobSF/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 215 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object has no attribute '__getitem__'

[2017-01-03 21:03:14]
[ERROR] Rendering to Template (/opt/MobSF/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 102 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object has no attribute '__getitem__'
```

I cloned from master, installed all dependencies and then run:

    python manage.py makemigrations 
    python manage.py migrate
    python manage.py runserver

After that I run the static analysis as following:

    python mass_static_analysis.py -d /path/to/apk -s localhost:8000

**Comment by ajinabraham** [comment]
Delete db.sqlite and try

```
python manage.py makemigrations 
python manage.py migrate
python manage.py runserver
```
go to http://127.0.0.1:8000 and initiate a new scan. Please don't upload a previously scanned APK.

**Comment by Emi1305** [comment]
I followed your instructions but the error persists

**Comment by ajinabraham** [comment]
This error occurs when database entries are not created properly

```
[INFO] Saving to Database

[2017-01-03 21:03:14]
[ERROR] Saving to DB (/opt/MobSF/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 215 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object has no attribute '__getitem__'

```

Try removing MobSF entirely and clone a fresh repo from master

**Comment by haroon-ali** [comment]
The error is persistent, I've deleted everything, redownloaded a fresh copy but still exists.
[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
	at strings.StringsXML.run(StringsXML.java:84)
	at strings.StringsXML.main(StringsXML.java:151)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 5 more

[INFO] Connecting to Database

[INFO] Saving to Database

**Comment by ajinabraham** [comment]
This is error is normal. `strings_from_apk.jar` fails on some APK. It's a normal behaviour.
