### ISSUE TITLE
Error "I/O operation failed." / "Could not find or load main class com.googlecode.dex2jar.tools.Dex2jarCmd"

### ISSUE THREAD

**Issue by cocaman** [ajinabraham/Mobile-Security-Framework-MobSF#52]
**System Information**
*Mobile-Security-Framework-MobSF 0.8.8 / latest git pull*

python --version
*Python 2.7.3*

java -version
*java version "1.8.0_60"*
*Java(TM) SE Runtime Environment (build 1.8.0_60-b27)*
*Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)*

uname -a
*Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux*

**Server Start**
python manage.py runserver

```bash
[INFO] Finding JDK Location in Linux/MAC....

[INFO] Oracle Java is installed!

[INFO] JDK 1.7 or above is available

[INFO] Finding JDK Location in Linux/MAC....

[INFO] Oracle Java is installed!

[INFO] JDK 1.7 or above is available
Performing system checks...

System check identified no issues (0 silenced).
September 10, 2015 - 04:10:35
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

**Console Log**
```bash
[INFO] Mobile Security Framework v0.8.8beta
[10/Sep/2015 04:19:01]"GET / HTTP/1.1" 200 7201
[INFO] MIME Type: application/octet-stream FILE: 09d9a04f6b322e3943efa4956bf35ef24cf74e6e5d5d58d907498461ac1c5501.bin.apk
[10/Sep/2015 04:19:10]"POST /Upload/ HTTP/1.1" 200 195
[INFO] Starting Analysis on : 09d9a04f6b322e3943efa4956bf35ef24cf74e6e5d5d58d907498461ac1c5501.bin.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Signer Certificate
[INFO] DEX -> JAR
Error: Could not find or load main class com.googlecode.dex2jar.tools.Dex2jarCmd
[INFO] DEX -> SMALI
[INFO] JAR -> JAVA
java.io.FileNotFoundException: /root/tools/Mobile-Security-Framework-MobSF/uploads/f99beeaf04052adcbd1ed13233e7db31/classes.jar (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at jd.core.Decompiler.decompile(Decompiler.java:28)
	at jd.core.Decompiler.decompileToDir(Decompiler.java:56)
	at jd.core.Main.main(Main.java:16)
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - /root/tools/Mobile-Security-Framework-MobSF/uploads/f99beeaf04052adcbd1ed13233e7db31/java_source/
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[10/Sep/2015 04:19:11]"GET /StaticAnalyzer/?name=09d9a04f6b322e3943efa4956bf35ef24cf74e6e5d5d58d907498461ac1c5501.bin.apk&type=apk&checksum=f99beeaf04052adcbd1ed13233e7db31 HTTP/1.1" 200 2948
```

**Comment by ajinabraham** [comment]
Fixed. Some problems with git. Dex2Jar lib directory was not uploaded.
Re download from :https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/releases/tag/0.8.8.1
