### ISSUE TITLE
UnsatisfiedLinkError (zlibVersion) while decompiling JAR -> JAVA

### ISSUE THREAD

**Issue by fikr4n** [ajinabraham/Mobile-Security-Framework-MobSF#85]
Here is the log:

```
[INFO] Finding JDK Location in Linux/MAC....

[INFO] Oracle Java is installed!

[INFO] JDK 1.7 or above is available

[INFO] Finding JDK Location in Linux/MAC....

[INFO] Oracle Java is installed!

[INFO] JDK 1.7 or above is available
Performing system checks...

System check identified no issues (0 silenced).
December 04, 2015 - 23:17:30
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[INFO] Starting Analysis on : my_app.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Signer Certificate
[INFO] DEX -> JAR
/opt/MobFS/uploads/deae12522af5bd82436162de10e81991/classes.jar exists, use --force to overwrite
[INFO] DEX -> SMALI
[INFO] JAR -> JAVA
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libjd-intellij8547526384205037372.so: /tmp/libjd-intellij8547526384205037372.so: undefined symbol: zlibVersion
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at com.jd.util.NativeUtils.loadLibraryFromJar(NativeUtils.java:94)
	at jd.ide.intellij.JavaDecompiler.<clinit>(JavaDecompiler.java:9)
	at jd.core.Decompiler.<init>(Decompiler.java:17)
	at jd.core.Main.main(Main.java:16)
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - /opt/MobFS/uploads/deae12522af5bd82436162de10e81991/java_source/
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
	at strings.StringsXML.run(StringsXML.java:84)
	at strings.StringsXML.main(StringsXML.java:151)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 5 more

[INFO] Connecting to Database

[INFO] Updating Database...
[04/Dec/2015 23:17:44]"GET /StaticAnalyzer/?checksum=deae12522af5bd82436162de10e81991&name=my_app.apk&type=apk&rescan=1 HTTP/1.1" 200 140502

```

There is also an error while extracting string, but it has been reported at issue #48.

Thank you very much

**Comment by ajinabraham** [comment]
This might be an issue with `jd-core`. Try using `cfr decompiler`.

Go to `MobSF/settings.py`

and change  `DECOMPILER = "jd-core"`  to `DECOMPILER = "cfr" ` and restart the server. After doing static analysis. Do a Rescan by pressing the `Rescan` Button.
If that is not working. delete the `db.sqlite` in the root directory, restart the server and do a static analysis.
