### ISSUE TITLE
OSError at /StaticAnalyzer_iOS/ when trying scan for IPA file

### ISSUE THREAD

**Issue by Arunraj89** [ajinabraham/Mobile-Security-Framework-MobSF#90]
Hi Ajin, I am trying to do an static scan for an .ipa file but i am getting a following error.
"[Errno 2] No such file or directory" . i am attaching the console output below:

[INFO] Mobile Security Framework v0.8.8beta
[23/Dec/2015 03:38:10] "GET / HTTP/1.1" 200 7201
[INFO] MIME Type: application/octet-stream FILE: ABC.ipa
[23/Dec/2015 03:38:20] "POST /Upload/ HTTP/1.1" 200 148
[INFO] iOS Static Analysis Started
[INFO] iOS Binary (IPA) Analysis Started
[INFO] Generating Hashes
[INFO] Extracting IPA
[INFO] Unzipping
[INFO] Get Files, BIN Plist -> XML, and Normalize
[INFO] Starting Binary Analysis
[INFO] Reading Info.plist
Error - while reading from Info.plist: encoding specified in XML declaration is incorrect: line 1, column 30
[INFO] iOS Binary : ABC Enterprise
[INFO] Running otool against the Binary
Internal Server Error: /StaticAnalyzer_iOS/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/macosx/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views.py", line 1527, in StaticAnalyzer_iOS
    INFO_PLIST,BIN_NAME,ID,VER,SDK,PLTFM,MIN,LIBS,BIN_ANAL=BinaryAnalysis(BIN_DIR,TOOLS_DIR,APP_DIR)
  File "/Users/macosx/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views.py", line 1841, in BinaryAnalysis
    dat=subprocess.check_output(args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 537, in check_output
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 679, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1228, in _execute_child
OSError: [Errno 2] No such file or directory
[23/Dec/2015 03:38:21] "GET /StaticAnalyzer_iOS/?name=ABC.ipa&type=ipa&checksum=d9e73601ed957ead969c7d1befd252ca HTTP/1.1" 500 88386

**Comment by ajinabraham** [comment]
do you have otool installed in mac?
Looks like the error happened here https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views.py#L1840
Let me know if it's not installed by default.

**Comment by Arunraj89** [comment]
No it's not installed by default... i don't have.

**Comment by ajinabraham** [comment]
You missed the documentation then. You must install Command Line Tools in OSX
http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

see the requirements https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/Documentation#requirements in wiki
